post_build:
  commands:
    - docker push $ECR_URI:latest
    - printf '[{"name":"springboot-container","imageUri":"%s"}]' $ECR_URI:latest > imagedefinitions.json
    - echo "CHECK FILE:"
    - cat imagedefinitions.json
    - ls -l
